# Generated by Django 5.1.7 on 2025-04-11 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_ac', models.CharField(max_length=50)),
                ('from_ac_name', models.CharField(max_length=60)),
                ('from_ac_routing_no', models.IntegerField()),
                ('to_ac', models.CharField(max_length=50)),
                ('to_ac_name', models.CharField(max_length=60)),
                ('to_ac_routing_no', models.IntegerField()),
                ('amount', models.FloatField()),
                ('service_charge', models.FloatField()),
                ('transaction_status', models.CharField(max_length=30)),
                ('created_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
