# Generated by Django 5.1.7 on 2025-04-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='from_ac_routing_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='to_ac_routing_no',
            field=models.CharField(max_length=20),
        ),
    ]
